name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/journal-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image tag
        id: set_tag
        run: echo "tag=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            --label "org.opencontainers.image.description=Journal IO Application" \
            --label "org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            --label "org.opencontainers.image.revision=${{ github.sha }}" \
            -t $IMAGE_NAME:${{ steps.set_tag.outputs.tag }} \
            -t $IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${{ steps.set_tag.outputs.tag }}
          docker push $IMAGE_NAME:latest

      - name: Save Docker image to tar (optional)
        run: docker save $IMAGE_NAME:latest -o journaling-app-latest.tar

      - name: Upload Docker image tar as artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: journaling-app-docker-image
          path: journaling-app-latest.tar
          retention-days: 1
